/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#565e74',
        'tertiary-container': '#370e00',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eceef0',
        'on-surface': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed': '#dae2fd',
        'tertiary-fixed': '#ffdbce',
        outline: '#76777d',
        'inverse-surface': '#2d3133',
        error: '#ba1a1a',
        background: '#f7f9fb',
        'primary-fixed-dim': '#bec6e0',
        primary: '#000000',
        'on-surface-variant': '#45464d',
        'surface-dim': '#d8dadc',
        'on-tertiary-container': '#e45405',
        'surface-container-high': '#e6e8ea',
        secondary: '#4b41e1',
        'inverse-primary': '#bec6e0',
        'surface-container-highest': '#e0e3e5',
        'on-secondary': '#ffffff',
        'on-background': '#191c1e',
        'secondary-fixed-dim': '#c3c0ff',
        'surface-variant': '#e0e3e5',
        tertiary: '#000000',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        surface: '#f7f9fb',
        'outline-variant': '#c6c6cd',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#ffb599',
        'on-secondary-container': '#fffbff',
        'secondary-container': '#645efb',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      maxWidth: {
        content: '65ch',
        wide: '72rem',
      },
    },
  },
  plugins: [],
};
